# Generated by Django 5.0.3 on 2024-10-14 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Locked", "LOcked"), ("Open", "Open")],
                        default="Locked",
                        max_length=6,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("tamper", "Tamper"), ("vibration", "Vibration")],
                        max_length=50,
                    ),
                ),
                ("detected_time", models.DateTimeField(auto_now_add=True)),
                (
                    "lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lock.lock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motion", models.FloatField()),
                ("vibration", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lock.lock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLockAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_granted", models.DateTimeField(auto_now_add=True)),
                (
                    "lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lock.lock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
